# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Pyqt5_example\TDC_I2C.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


import sys
import time
import socket
import winsound
from ETROC1_TDCReg import *
from command_interpret import *
from PyQt5 import QtCore, QtGui, QtWidgets
'''
@author: Wei Zhang
@date: 2019-12-13
This script is used for testing ETROC1 TDC chip. The mianly function of this script is I2C write and read, Ethernet communication, instrument control and so on.
'''
hostname = '192.168.2.3'					#FPGA IP address
port = 1024									#port number
I2C_Subordinate_Addr = 0x22
#--------------------------------------------------------------------------#
## IIC write subordinate device
# @param mode[1:0] : '0'is 1 bytes read or wirte, '1' is 2 bytes read or write, '2' is 3 bytes read or write
# @param subordinate[7:0] : subordinate device address
# @param wr: 1-bit '0' is write, '1' is read
# @param reg_addr[7:0] : register address
# @param data[7:0] : 8-bit write data
def iic_write(mode, subordinate_addr, wr, reg_addr, data):
    val = mode << 24 | subordinate_addr << 17 | wr << 16 | reg_addr << 8 | data
    cmd_interpret.write_config_reg(4, 0xffff & val)
    cmd_interpret.write_config_reg(5, 0xffff & (val>>16))
    time.sleep(0.01)
    cmd_interpret.write_pulse_reg(0x0001)           # reset ddr3 data fifo
    time.sleep(0.01)
    # print(hex(val))
#--------------------------------------------------------------------------#
## IIC read subordinate device
# @param mode[1:0] : '0'is 1 bytes read or wirte, '1' is 2 bytes read or write, '2' is 3 bytes read or write
# @param subordinate[7:0]: subordinate device address
# @param wr: 1-bit '0' is write, '1' is read
# @param reg_addr[7:0] : register address
def iic_read(mode, subordinate_addr, wr, reg_addr):
    val = mode << 24 | subordinate_addr << 17 |  0 << 16 | reg_addr << 8 | 0x00	  # write device addr and reg addr
    cmd_interpret.write_config_reg(4, 0xffff & val)
    cmd_interpret.write_config_reg(5, 0xffff & (val>>16))
    time.sleep(0.01)
    cmd_interpret.write_pulse_reg(0x0001)				                      # Sent a pulse to IIC module

    val = mode << 24 | subordinate_addr << 17 | wr << 16 | reg_addr << 8 | 0x00	  # write device addr and read one byte
    cmd_interpret.write_config_reg(4, 0xffff & val)
    cmd_interpret.write_config_reg(5, 0xffff & (val>>16))
    time.sleep(0.01)
    cmd_interpret.write_pulse_reg(0x0001)				                      # Sent a pulse to IIC module
    time.sleep(0.01)									                      # delay 10ns then to read data
    return cmd_interpret.read_status_reg(0) & 0xff
#--------------------------------------------------------------------------#
class Ui_ETROC1_TDC_TEST_GUI(object):
    def setupUi(self, ETROC1_TDC_TEST_GUI):
        ETROC1_TDC_TEST_GUI.setObjectName("ETROC1_TDC_TEST_GUI")
        ETROC1_TDC_TEST_GUI.resize(899, 789)
        self.centralwidget = QtWidgets.QWidget(ETROC1_TDC_TEST_GUI)
        self.centralwidget.setObjectName("centralwidget")
        self.Dataout_AmplSel = QtWidgets.QSpinBox(self.centralwidget)
        self.Dataout_AmplSel.setGeometry(QtCore.QRect(160, 420, 42, 22))
        self.Dataout_AmplSel.setMaximum(7)
        self.Dataout_AmplSel.setProperty("value", 1)
        self.Dataout_AmplSel.setObjectName("Dataout_AmplSel")
        self.Dataout_AmplSel_Label = QtWidgets.QLabel(self.centralwidget)
        self.Dataout_AmplSel_Label.setGeometry(QtCore.QRect(26, 420, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Dataout_AmplSel_Label.setFont(font)
        self.Dataout_AmplSel_Label.setObjectName("Dataout_AmplSel_Label")
        self.Clk40Mout_disCMLDriver_BIAS_Label = QtWidgets.QLabel(self.centralwidget)
        self.Clk40Mout_disCMLDriver_BIAS_Label.setGeometry(QtCore.QRect(660, 420, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Clk40Mout_disCMLDriver_BIAS_Label.setFont(font)
        self.Clk40Mout_disCMLDriver_BIAS_Label.setObjectName("Clk40Mout_disCMLDriver_BIAS_Label")
        self.Clk40Mout_disCMLDriver_BIAS = QtWidgets.QSpinBox(self.centralwidget)
        self.Clk40Mout_disCMLDriver_BIAS.setGeometry(QtCore.QRect(840, 420, 42, 22))
        self.Clk40Mout_disCMLDriver_BIAS.setMaximum(1)
        self.Clk40Mout_disCMLDriver_BIAS.setObjectName("Clk40Mout_disCMLDriver_BIAS")
        self.Input_eRx_Configuration_Label = QtWidgets.QLabel(self.centralwidget)
        self.Input_eRx_Configuration_Label.setGeometry(QtCore.QRect(10, 0, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Input_eRx_Configuration_Label.setFont(font)
        self.Input_eRx_Configuration_Label.setObjectName("Input_eRx_Configuration_Label")
        self.Pulse_enableRx = QtWidgets.QSpinBox(self.centralwidget)
        self.Pulse_enableRx.setGeometry(QtCore.QRect(160, 30, 42, 22))
        self.Pulse_enableRx.setMaximum(1)
        self.Pulse_enableRx.setProperty("value", 1)
        self.Pulse_enableRx.setObjectName("Pulse_enableRx")
        self.Pulse_enableRx_Label = QtWidgets.QLabel(self.centralwidget)
        self.Pulse_enableRx_Label.setGeometry(QtCore.QRect(10, 30, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Pulse_enableRx_Label.setFont(font)
        self.Pulse_enableRx_Label.setObjectName("Pulse_enableRx_Label")
        self.Pulse_invertData = QtWidgets.QSpinBox(self.centralwidget)
        self.Pulse_invertData.setGeometry(QtCore.QRect(160, 60, 42, 22))
        self.Pulse_invertData.setMaximum(1)
        self.Pulse_invertData.setObjectName("Pulse_invertData")
        self.Pulse_invertData_Label = QtWidgets.QLabel(self.centralwidget)
        self.Pulse_invertData_Label.setGeometry(QtCore.QRect(10, 60, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Pulse_invertData_Label.setFont(font)
        self.Pulse_invertData_Label.setObjectName("Pulse_invertData_Label")
        self.Pulse_enableTermination = QtWidgets.QSpinBox(self.centralwidget)
        self.Pulse_enableTermination.setGeometry(QtCore.QRect(160, 90, 42, 22))
        self.Pulse_enableTermination.setMaximum(1)
        self.Pulse_enableTermination.setProperty("value", 1)
        self.Pulse_enableTermination.setObjectName("Pulse_enableTermination")
        self.Pulse_enableTermination_Label = QtWidgets.QLabel(self.centralwidget)
        self.Pulse_enableTermination_Label.setGeometry(QtCore.QRect(10, 90, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Pulse_enableTermination_Label.setFont(font)
        self.Pulse_enableTermination_Label.setObjectName("Pulse_enableTermination_Label")
        self.Pulse_setCommonMode_Label = QtWidgets.QLabel(self.centralwidget)
        self.Pulse_setCommonMode_Label.setGeometry(QtCore.QRect(10, 120, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Pulse_setCommonMode_Label.setFont(font)
        self.Pulse_setCommonMode_Label.setObjectName("Pulse_setCommonMode_Label")
        self.Pulse_setCommonMode = QtWidgets.QSpinBox(self.centralwidget)
        self.Pulse_setCommonMode.setGeometry(QtCore.QRect(160, 120, 42, 22))
        self.Pulse_setCommonMode.setMaximum(1)
        self.Pulse_setCommonMode.setProperty("value", 1)
        self.Pulse_setCommonMode.setObjectName("Pulse_setCommonMode")
        self.Pulse_equalizer_Label = QtWidgets.QLabel(self.centralwidget)
        self.Pulse_equalizer_Label.setGeometry(QtCore.QRect(10, 150, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Pulse_equalizer_Label.setFont(font)
        self.Pulse_equalizer_Label.setObjectName("Pulse_equalizer_Label")
        self.Pulse_equalizer = QtWidgets.QSpinBox(self.centralwidget)
        self.Pulse_equalizer.setGeometry(QtCore.QRect(160, 150, 42, 22))
        self.Pulse_equalizer.setMaximum(3)
        self.Pulse_equalizer.setObjectName("Pulse_equalizer")
        self.Clk40M_equalizer_Label = QtWidgets.QLabel(self.centralwidget)
        self.Clk40M_equalizer_Label.setGeometry(QtCore.QRect(220, 150, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Clk40M_equalizer_Label.setFont(font)
        self.Clk40M_equalizer_Label.setObjectName("Clk40M_equalizer_Label")
        self.Clk40M_setCommonMode_Label = QtWidgets.QLabel(self.centralwidget)
        self.Clk40M_setCommonMode_Label.setGeometry(QtCore.QRect(220, 120, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Clk40M_setCommonMode_Label.setFont(font)
        self.Clk40M_setCommonMode_Label.setObjectName("Clk40M_setCommonMode_Label")
        self.Clk40M_enableTermination_Label = QtWidgets.QLabel(self.centralwidget)
        self.Clk40M_enableTermination_Label.setGeometry(QtCore.QRect(220, 90, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Clk40M_enableTermination_Label.setFont(font)
        self.Clk40M_enableTermination_Label.setObjectName("Clk40M_enableTermination_Label")
        self.Clk40M_equalizer = QtWidgets.QSpinBox(self.centralwidget)
        self.Clk40M_equalizer.setGeometry(QtCore.QRect(380, 150, 42, 22))
        self.Clk40M_equalizer.setMaximum(3)
        self.Clk40M_equalizer.setObjectName("Clk40M_equalizer")
        self.Clk40M_enableTermination = QtWidgets.QSpinBox(self.centralwidget)
        self.Clk40M_enableTermination.setGeometry(QtCore.QRect(380, 90, 42, 22))
        self.Clk40M_enableTermination.setMaximum(1)
        self.Clk40M_enableTermination.setProperty("value", 1)
        self.Clk40M_enableTermination.setObjectName("Clk40M_enableTermination")
        self.Clk40M_invertData = QtWidgets.QSpinBox(self.centralwidget)
        self.Clk40M_invertData.setGeometry(QtCore.QRect(380, 60, 42, 22))
        self.Clk40M_invertData.setMaximum(1)
        self.Clk40M_invertData.setObjectName("Clk40M_invertData")
        self.Clk40M_setCommonMode = QtWidgets.QSpinBox(self.centralwidget)
        self.Clk40M_setCommonMode.setGeometry(QtCore.QRect(380, 120, 42, 22))
        self.Clk40M_setCommonMode.setMaximum(1)
        self.Clk40M_setCommonMode.setProperty("value", 1)
        self.Clk40M_setCommonMode.setObjectName("Clk40M_setCommonMode")
        self.Clk40M_invertData_Label = QtWidgets.QLabel(self.centralwidget)
        self.Clk40M_invertData_Label.setGeometry(QtCore.QRect(220, 60, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Clk40M_invertData_Label.setFont(font)
        self.Clk40M_invertData_Label.setObjectName("Clk40M_invertData_Label")
        self.Clk40M_enableRx = QtWidgets.QSpinBox(self.centralwidget)
        self.Clk40M_enableRx.setGeometry(QtCore.QRect(380, 30, 42, 22))
        self.Clk40M_enableRx.setMaximum(1)
        self.Clk40M_enableRx.setProperty("value", 1)
        self.Clk40M_enableRx.setObjectName("Clk40M_enableRx")
        self.Clk40M_enableRx_Labe = QtWidgets.QLabel(self.centralwidget)
        self.Clk40M_enableRx_Labe.setGeometry(QtCore.QRect(220, 30, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Clk40M_enableRx_Labe.setFont(font)
        self.Clk40M_enableRx_Labe.setObjectName("Clk40M_enableRx_Labe")
        self.Clk320M_setCommonMode_Label = QtWidgets.QLabel(self.centralwidget)
        self.Clk320M_setCommonMode_Label.setGeometry(QtCore.QRect(440, 120, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Clk320M_setCommonMode_Label.setFont(font)
        self.Clk320M_setCommonMode_Label.setObjectName("Clk320M_setCommonMode_Label")
        self.Clk320M_equalizer_Label = QtWidgets.QLabel(self.centralwidget)
        self.Clk320M_equalizer_Label.setGeometry(QtCore.QRect(440, 150, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Clk320M_equalizer_Label.setFont(font)
        self.Clk320M_equalizer_Label.setObjectName("Clk320M_equalizer_Label")
        self.Clk320M_enableTermination = QtWidgets.QSpinBox(self.centralwidget)
        self.Clk320M_enableTermination.setGeometry(QtCore.QRect(610, 90, 42, 22))
        self.Clk320M_enableTermination.setMaximum(1)
        self.Clk320M_enableTermination.setProperty("value", 1)
        self.Clk320M_enableTermination.setObjectName("Clk320M_enableTermination")
        self.Clk320M_invertData = QtWidgets.QSpinBox(self.centralwidget)
        self.Clk320M_invertData.setGeometry(QtCore.QRect(610, 60, 42, 22))
        self.Clk320M_invertData.setMaximum(1)
        self.Clk320M_invertData.setObjectName("Clk320M_invertData")
        self.Clk320M_enableRx = QtWidgets.QSpinBox(self.centralwidget)
        self.Clk320M_enableRx.setGeometry(QtCore.QRect(610, 30, 42, 22))
        self.Clk320M_enableRx.setMaximum(1)
        self.Clk320M_enableRx.setProperty("value", 1)
        self.Clk320M_enableRx.setObjectName("Clk320M_enableRx")
        self.Clk320M_setCommonMode = QtWidgets.QSpinBox(self.centralwidget)
        self.Clk320M_setCommonMode.setGeometry(QtCore.QRect(610, 120, 42, 22))
        self.Clk320M_setCommonMode.setMaximum(1)
        self.Clk320M_setCommonMode.setProperty("value", 1)
        self.Clk320M_setCommonMode.setObjectName("Clk320M_setCommonMode")
        self.Clk320M_enableTermination_Label = QtWidgets.QLabel(self.centralwidget)
        self.Clk320M_enableTermination_Label.setGeometry(QtCore.QRect(440, 90, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Clk320M_enableTermination_Label.setFont(font)
        self.Clk320M_enableTermination_Label.setObjectName("Clk320M_enableTermination_Label")
        self.Clk320M_equalizer = QtWidgets.QSpinBox(self.centralwidget)
        self.Clk320M_equalizer.setGeometry(QtCore.QRect(610, 150, 42, 22))
        self.Clk320M_equalizer.setMaximum(3)
        self.Clk320M_equalizer.setObjectName("Clk320M_equalizer")
        self.Clk320M_invertData_Label = QtWidgets.QLabel(self.centralwidget)
        self.Clk320M_invertData_Label.setGeometry(QtCore.QRect(440, 60, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Clk320M_invertData_Label.setFont(font)
        self.Clk320M_invertData_Label.setObjectName("Clk320M_invertData_Label")
        self.Clk320M_enableRx_Label = QtWidgets.QLabel(self.centralwidget)
        self.Clk320M_enableRx_Label.setGeometry(QtCore.QRect(440, 30, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Clk320M_enableRx_Label.setFont(font)
        self.Clk320M_enableRx_Label.setObjectName("Clk320M_enableRx_Label")
        self.Clk1G28_enableTermination = QtWidgets.QSpinBox(self.centralwidget)
        self.Clk1G28_enableTermination.setGeometry(QtCore.QRect(840, 90, 42, 22))
        self.Clk1G28_enableTermination.setMaximum(1)
        self.Clk1G28_enableTermination.setProperty("value", 1)
        self.Clk1G28_enableTermination.setObjectName("Clk1G28_enableTermination")
        self.Clk1G28_setCommonMode_Label = QtWidgets.QLabel(self.centralwidget)
        self.Clk1G28_setCommonMode_Label.setGeometry(QtCore.QRect(670, 120, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Clk1G28_setCommonMode_Label.setFont(font)
        self.Clk1G28_setCommonMode_Label.setObjectName("Clk1G28_setCommonMode_Label")
        self.Clk1G28_enableRx = QtWidgets.QSpinBox(self.centralwidget)
        self.Clk1G28_enableRx.setGeometry(QtCore.QRect(840, 30, 42, 22))
        self.Clk1G28_enableRx.setMaximum(1)
        self.Clk1G28_enableRx.setProperty("value", 1)
        self.Clk1G28_enableRx.setObjectName("Clk1G28_enableRx")
        self.Clk1G28_equalizer_Label = QtWidgets.QLabel(self.centralwidget)
        self.Clk1G28_equalizer_Label.setGeometry(QtCore.QRect(670, 150, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Clk1G28_equalizer_Label.setFont(font)
        self.Clk1G28_equalizer_Label.setObjectName("Clk1G28_equalizer_Label")
        self.Clk1G28_invertData = QtWidgets.QSpinBox(self.centralwidget)
        self.Clk1G28_invertData.setGeometry(QtCore.QRect(840, 60, 42, 22))
        self.Clk1G28_invertData.setMaximum(1)
        self.Clk1G28_invertData.setObjectName("Clk1G28_invertData")
        self.Clk1G28_equalizer = QtWidgets.QSpinBox(self.centralwidget)
        self.Clk1G28_equalizer.setGeometry(QtCore.QRect(840, 150, 42, 22))
        self.Clk1G28_equalizer.setMaximum(3)
        self.Clk1G28_equalizer.setObjectName("Clk1G28_equalizer")
        self.Clk1G28_enableTermination_Label = QtWidgets.QLabel(self.centralwidget)
        self.Clk1G28_enableTermination_Label.setGeometry(QtCore.QRect(670, 90, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Clk1G28_enableTermination_Label.setFont(font)
        self.Clk1G28_enableTermination_Label.setObjectName("Clk1G28_enableTermination_Label")
        self.Clk1G28_setCommonMode = QtWidgets.QSpinBox(self.centralwidget)
        self.Clk1G28_setCommonMode.setGeometry(QtCore.QRect(840, 120, 42, 22))
        self.Clk1G28_setCommonMode.setMaximum(1)
        self.Clk1G28_setCommonMode.setProperty("value", 1)
        self.Clk1G28_setCommonMode.setObjectName("Clk1G28_setCommonMode")
        self.Clk1G28_invertData_Label = QtWidgets.QLabel(self.centralwidget)
        self.Clk1G28_invertData_Label.setGeometry(QtCore.QRect(670, 60, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Clk1G28_invertData_Label.setFont(font)
        self.Clk1G28_invertData_Label.setObjectName("Clk1G28_invertData_Label")
        self.Clk1G28_enableRx_Label = QtWidgets.QLabel(self.centralwidget)
        self.Clk1G28_enableRx_Label.setGeometry(QtCore.QRect(670, 30, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Clk1G28_enableRx_Label.setFont(font)
        self.Clk1G28_enableRx_Label.setObjectName("Clk1G28_enableRx_Label")
        self.TDC_Configuration_Label = QtWidgets.QLabel(self.centralwidget)
        self.TDC_Configuration_Label.setGeometry(QtCore.QRect(10, 180, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.TDC_Configuration_Label.setFont(font)
        self.TDC_Configuration_Label.setObjectName("TDC_Configuration_Label")
        self.TDC_enable = QtWidgets.QSpinBox(self.centralwidget)
        self.TDC_enable.setGeometry(QtCore.QRect(160, 210, 42, 22))
        self.TDC_enable.setMaximum(1)
        self.TDC_enable.setProperty("value", 1)
        self.TDC_enable.setObjectName("TDC_enable")
        self.TDC_enable_Label = QtWidgets.QLabel(self.centralwidget)
        self.TDC_enable_Label.setGeometry(QtCore.QRect(82, 210, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TDC_enable_Label.setFont(font)
        self.TDC_enable_Label.setObjectName("TDC_enable_Label")
        self.TDC_testMode_Label = QtWidgets.QLabel(self.centralwidget)
        self.TDC_testMode_Label.setGeometry(QtCore.QRect(288, 210, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TDC_testMode_Label.setFont(font)
        self.TDC_testMode_Label.setObjectName("TDC_testMode_Label")
        self.TDC_testMode = QtWidgets.QSpinBox(self.centralwidget)
        self.TDC_testMode.setGeometry(QtCore.QRect(380, 210, 42, 22))
        self.TDC_testMode.setMaximum(1)
        self.TDC_testMode.setProperty("value", 0)
        self.TDC_testMode.setObjectName("TDC_testMode")
        self.TDC_selRawCode_Label = QtWidgets.QLabel(self.centralwidget)
        self.TDC_selRawCode_Label.setGeometry(QtCore.QRect(500, 210, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TDC_selRawCode_Label.setFont(font)
        self.TDC_selRawCode_Label.setObjectName("TDC_selRawCode_Label")
        self.TDC_selRawCode = QtWidgets.QSpinBox(self.centralwidget)
        self.TDC_selRawCode.setGeometry(QtCore.QRect(610, 210, 42, 22))
        self.TDC_selRawCode.setMaximum(1)
        self.TDC_selRawCode.setProperty("value", 0)
        self.TDC_selRawCode.setObjectName("TDC_selRawCode")
        self.TDC_resetn = QtWidgets.QSpinBox(self.centralwidget)
        self.TDC_resetn.setGeometry(QtCore.QRect(840, 210, 42, 22))
        self.TDC_resetn.setMaximum(1)
        self.TDC_resetn.setProperty("value", 1)
        self.TDC_resetn.setObjectName("TDC_resetn")
        self.TDC_resetn_Label = QtWidgets.QLabel(self.centralwidget)
        self.TDC_resetn_Label.setGeometry(QtCore.QRect(764, 210, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TDC_resetn_Label.setFont(font)
        self.TDC_resetn_Label.setObjectName("TDC_resetn_Label")
        self.TDC_enableMon_Label = QtWidgets.QLabel(self.centralwidget)
        self.TDC_enableMon_Label.setGeometry(QtCore.QRect(507, 240, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TDC_enableMon_Label.setFont(font)
        self.TDC_enableMon_Label.setObjectName("TDC_enableMon_Label")
        self.TDC_polaritySel_Label = QtWidgets.QLabel(self.centralwidget)
        self.TDC_polaritySel_Label.setGeometry(QtCore.QRect(60, 240, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TDC_polaritySel_Label.setFont(font)
        self.TDC_polaritySel_Label.setObjectName("TDC_polaritySel_Label")
        self.TDC_enableMon = QtWidgets.QSpinBox(self.centralwidget)
        self.TDC_enableMon.setGeometry(QtCore.QRect(610, 240, 42, 22))
        self.TDC_enableMon.setMaximum(1)
        self.TDC_enableMon.setProperty("value", 0)
        self.TDC_enableMon.setObjectName("TDC_enableMon")
        self.TDC_autoReset = QtWidgets.QSpinBox(self.centralwidget)
        self.TDC_autoReset.setGeometry(QtCore.QRect(380, 240, 42, 22))
        self.TDC_autoReset.setMaximum(1)
        self.TDC_autoReset.setProperty("value", 0)
        self.TDC_autoReset.setObjectName("TDC_autoReset")
        self.TDC_polaritySel = QtWidgets.QSpinBox(self.centralwidget)
        self.TDC_polaritySel.setGeometry(QtCore.QRect(160, 240, 42, 22))
        self.TDC_polaritySel.setMaximum(1)
        self.TDC_polaritySel.setProperty("value", 1)
        self.TDC_polaritySel.setObjectName("TDC_polaritySel")
        self.TDC_autoReset_Label = QtWidgets.QLabel(self.centralwidget)
        self.TDC_autoReset_Label.setGeometry(QtCore.QRect(282, 240, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TDC_autoReset_Label.setFont(font)
        self.TDC_autoReset_Label.setObjectName("TDC_autoReset_Label")
        self.TDC_timeStampMode = QtWidgets.QSpinBox(self.centralwidget)
        self.TDC_timeStampMode.setGeometry(QtCore.QRect(840, 240, 42, 22))
        self.TDC_timeStampMode.setMaximum(1)
        self.TDC_timeStampMode.setProperty("value", 1)
        self.TDC_timeStampMode.setObjectName("TDC_timeStampMode")
        self.TDC_level_Label = QtWidgets.QLabel(self.centralwidget)
        self.TDC_level_Label.setGeometry(QtCore.QRect(66, 270, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TDC_level_Label.setFont(font)
        self.TDC_level_Label.setObjectName("TDC_level_Label")
        self.TDC_offset = QtWidgets.QSpinBox(self.centralwidget)
        self.TDC_offset.setGeometry(QtCore.QRect(380, 270, 42, 22))
        self.TDC_offset.setMaximum(127)
        self.TDC_offset.setProperty("value", 0)
        self.TDC_offset.setObjectName("TDC_offset")
        self.TDC_leve = QtWidgets.QSpinBox(self.centralwidget)
        self.TDC_leve.setGeometry(QtCore.QRect(160, 270, 42, 22))
        self.TDC_leve.setMaximum(7)
        self.TDC_leve.setProperty("value", 1)
        self.TDC_leve.setObjectName("TDC_leve")
        self.TDC_timeStampMode_Label = QtWidgets.QLabel(self.centralwidget)
        self.TDC_timeStampMode_Label.setGeometry(QtCore.QRect(707, 240, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TDC_timeStampMode_Label.setFont(font)
        self.TDC_timeStampMode_Label.setObjectName("TDC_timeStampMode_Label")
        self.TDC_offset_Label = QtWidgets.QLabel(self.centralwidget)
        self.TDC_offset_Label.setGeometry(QtCore.QRect(279, 270, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TDC_offset_Label.setFont(font)
        self.TDC_offset_Label.setObjectName("TDC_offset_Label")
        self.DMRO_Configuration_Label = QtWidgets.QLabel(self.centralwidget)
        self.DMRO_Configuration_Label.setGeometry(QtCore.QRect(10, 300, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DMRO_Configuration_Label.setFont(font)
        self.DMRO_Configuration_Label.setObjectName("DMRO_Configuration_Label")
        self.DMRO_resetn_Label = QtWidgets.QLabel(self.centralwidget)
        self.DMRO_resetn_Label.setGeometry(QtCore.QRect(754, 330, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DMRO_resetn_Label.setFont(font)
        self.DMRO_resetn_Label.setObjectName("DMRO_resetn_Label")
        self.DMRO_enable_Label = QtWidgets.QLabel(self.centralwidget)
        self.DMRO_enable_Label.setGeometry(QtCore.QRect(70, 330, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DMRO_enable_Label.setFont(font)
        self.DMRO_enable_Label.setObjectName("DMRO_enable_Label")
        self.DMRO_enable = QtWidgets.QSpinBox(self.centralwidget)
        self.DMRO_enable.setGeometry(QtCore.QRect(160, 330, 42, 22))
        self.DMRO_enable.setMaximum(1)
        self.DMRO_enable.setProperty("value", 1)
        self.DMRO_enable.setObjectName("DMRO_enable")
        self.DMRO_testMode_Label = QtWidgets.QLabel(self.centralwidget)
        self.DMRO_testMode_Label.setGeometry(QtCore.QRect(277, 330, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DMRO_testMode_Label.setFont(font)
        self.DMRO_testMode_Label.setObjectName("DMRO_testMode_Label")
        self.DMRO_resetn = QtWidgets.QSpinBox(self.centralwidget)
        self.DMRO_resetn.setGeometry(QtCore.QRect(840, 330, 42, 22))
        self.DMRO_resetn.setMaximum(1)
        self.DMRO_resetn.setProperty("value", 1)
        self.DMRO_resetn.setObjectName("DMRO_resetn")
        self.DMRO_reverse = QtWidgets.QSpinBox(self.centralwidget)
        self.DMRO_reverse.setGeometry(QtCore.QRect(610, 330, 42, 22))
        self.DMRO_reverse.setMaximum(1)
        self.DMRO_reverse.setProperty("value", 0)
        self.DMRO_reverse.setObjectName("DMRO_reverse")
        self.DMRO_testMode = QtWidgets.QSpinBox(self.centralwidget)
        self.DMRO_testMode.setGeometry(QtCore.QRect(380, 330, 42, 22))
        self.DMRO_testMode.setMaximum(1)
        self.DMRO_testMode.setProperty("value", 0)
        self.DMRO_testMode.setObjectName("DMRO_testMode")
        self.DMRO_reverse_Label = QtWidgets.QLabel(self.centralwidget)
        self.DMRO_reverse_Label.setGeometry(QtCore.QRect(516, 330, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DMRO_reverse_Label.setFont(font)
        self.DMRO_reverse_Label.setObjectName("DMRO_reverse_Label")
        self.DMRO_revclk_Label = QtWidgets.QLabel(self.centralwidget)
        self.DMRO_revclk_Label.setGeometry(QtCore.QRect(74, 360, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DMRO_revclk_Label.setFont(font)
        self.DMRO_revclk_Label.setObjectName("DMRO_revclk_Label")
        self.DMRO_revclk = QtWidgets.QSpinBox(self.centralwidget)
        self.DMRO_revclk.setGeometry(QtCore.QRect(160, 360, 42, 22))
        self.DMRO_revclk.setMaximum(1)
        self.DMRO_revclk.setProperty("value", 0)
        self.DMRO_revclk.setObjectName("DMRO_revclk")
        self.Output_TX_Configuration_Labe = QtWidgets.QLabel(self.centralwidget)
        self.Output_TX_Configuration_Labe.setGeometry(QtCore.QRect(10, 390, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Output_TX_Configuration_Labe.setFont(font)
        self.Output_TX_Configuration_Labe.setObjectName("Output_TX_Configuration_Labe")
        self.Dataout_disCMLDriver_BIAS_Label = QtWidgets.QLabel(self.centralwidget)
        self.Dataout_disCMLDriver_BIAS_Label.setGeometry(QtCore.QRect(215, 420, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Dataout_disCMLDriver_BIAS_Label.setFont(font)
        self.Dataout_disCMLDriver_BIAS_Label.setObjectName("Dataout_disCMLDriver_BIAS_Label")
        self.Dataout_disCMLDriver_BIAS = QtWidgets.QSpinBox(self.centralwidget)
        self.Dataout_disCMLDriver_BIAS.setGeometry(QtCore.QRect(380, 420, 42, 22))
        self.Dataout_disCMLDriver_BIAS.setMaximum(1)
        self.Dataout_disCMLDriver_BIAS.setObjectName("Dataout_disCMLDriver_BIAS")
        self.Clk40Mout_AmplSel_Label = QtWidgets.QLabel(self.centralwidget)
        self.Clk40Mout_AmplSel_Label.setGeometry(QtCore.QRect(460, 420, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Clk40Mout_AmplSel_Label.setFont(font)
        self.Clk40Mout_AmplSel_Label.setObjectName("Clk40Mout_AmplSel_Label")
        self.Clk40Mout_AmplSel = QtWidgets.QSpinBox(self.centralwidget)
        self.Clk40Mout_AmplSel.setGeometry(QtCore.QRect(610, 420, 42, 22))
        self.Clk40Mout_AmplSel.setMaximum(7)
        self.Clk40Mout_AmplSel.setProperty("value", 1)
        self.Clk40Mout_AmplSel.setObjectName("Clk40Mout_AmplSel")
        self.Clock_Configuration_Label = QtWidgets.QLabel(self.centralwidget)
        self.Clock_Configuration_Label.setGeometry(QtCore.QRect(10, 480, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Clock_Configuration_Label.setFont(font)
        self.Clock_Configuration_Label.setObjectName("Clock_Configuration_Label")
        self.Clk40M_Psel_Label = QtWidgets.QLabel(self.centralwidget)
        self.Clk40M_Psel_Label.setGeometry(QtCore.QRect(300, 510, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Clk40M_Psel_Label.setFont(font)
        self.Clk40M_Psel_Label.setObjectName("Clk40M_Psel_Label")
        self.Clk40M_Sel_Label = QtWidgets.QLabel(self.centralwidget)
        self.Clk40M_Sel_Label.setGeometry(QtCore.QRect(86, 510, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Clk40M_Sel_Label.setFont(font)
        self.Clk40M_Sel_Label.setObjectName("Clk40M_Sel_Label")
        self.Clk320M_Sel_Label = QtWidgets.QLabel(self.centralwidget)
        self.Clk320M_Sel_Label.setGeometry(QtCore.QRect(528, 510, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Clk320M_Sel_Label.setFont(font)
        self.Clk320M_Sel_Label.setObjectName("Clk320M_Sel_Label")
        self.Clk40M_Sel = QtWidgets.QSpinBox(self.centralwidget)
        self.Clk40M_Sel.setGeometry(QtCore.QRect(160, 510, 42, 22))
        self.Clk40M_Sel.setMaximum(1)
        self.Clk40M_Sel.setProperty("value", 1)
        self.Clk40M_Sel.setObjectName("Clk40M_Sel")
        self.Clk320M_Psel = QtWidgets.QSpinBox(self.centralwidget)
        self.Clk320M_Psel.setGeometry(QtCore.QRect(840, 510, 42, 22))
        self.Clk320M_Psel.setMaximum(1)
        self.Clk320M_Psel.setProperty("value", 1)
        self.Clk320M_Psel.setObjectName("Clk320M_Psel")
        self.Clk320M_Psel_Label = QtWidgets.QLabel(self.centralwidget)
        self.Clk320M_Psel_Label.setGeometry(QtCore.QRect(753, 510, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Clk320M_Psel_Label.setFont(font)
        self.Clk320M_Psel_Label.setObjectName("Clk320M_Psel_Label")
        self.Clk40M_Psel = QtWidgets.QSpinBox(self.centralwidget)
        self.Clk40M_Psel.setGeometry(QtCore.QRect(380, 510, 42, 22))
        self.Clk40M_Psel.setMaximum(1)
        self.Clk40M_Psel.setProperty("value", 1)
        self.Clk40M_Psel.setObjectName("Clk40M_Psel")
        self.Clk320M_Sel = QtWidgets.QSpinBox(self.centralwidget)
        self.Clk320M_Sel.setGeometry(QtCore.QRect(610, 510, 42, 22))
        self.Clk320M_Sel.setMaximum(1)
        self.Clk320M_Sel.setProperty("value", 1)
        self.Clk320M_Sel.setObjectName("Clk320M_Sel")
        self.GROout_disCMLDriver_BIAS_Label = QtWidgets.QLabel(self.centralwidget)
        self.GROout_disCMLDriver_BIAS_Label.setGeometry(QtCore.QRect(215, 450, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.GROout_disCMLDriver_BIAS_Label.setFont(font)
        self.GROout_disCMLDriver_BIAS_Label.setObjectName("GROout_disCMLDriver_BIAS_Label")
        self.GROout_AmplSel_Label = QtWidgets.QLabel(self.centralwidget)
        self.GROout_AmplSel_Label.setGeometry(QtCore.QRect(27, 450, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.GROout_AmplSel_Label.setFont(font)
        self.GROout_AmplSel_Label.setObjectName("GROout_AmplSel_Label")
        self.Dataout_Sel_Label = QtWidgets.QLabel(self.centralwidget)
        self.Dataout_Sel_Label.setGeometry(QtCore.QRect(533, 450, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Dataout_Sel_Label.setFont(font)
        self.Dataout_Sel_Label.setObjectName("Dataout_Sel_Label")
        self.GROout_AmplSel = QtWidgets.QSpinBox(self.centralwidget)
        self.GROout_AmplSel.setGeometry(QtCore.QRect(160, 450, 42, 22))
        self.GROout_AmplSel.setMaximum(7)
        self.GROout_AmplSel.setProperty("value", 1)
        self.GROout_AmplSel.setObjectName("GROout_AmplSel")
        self.GROout_disCMLDriver_BIAS = QtWidgets.QSpinBox(self.centralwidget)
        self.GROout_disCMLDriver_BIAS.setGeometry(QtCore.QRect(380, 450, 42, 22))
        self.GROout_disCMLDriver_BIAS.setMaximum(1)
        self.GROout_disCMLDriver_BIAS.setObjectName("GROout_disCMLDriver_BIAS")
        self.Dataout_Sel = QtWidgets.QSpinBox(self.centralwidget)
        self.Dataout_Sel.setGeometry(QtCore.QRect(610, 450, 42, 22))
        self.Dataout_Sel.setMaximum(1)
        self.Dataout_Sel.setProperty("value", 1)
        self.Dataout_Sel.setObjectName("Dataout_Sel")
        self.GRO_TOA_CK = QtWidgets.QSpinBox(self.centralwidget)
        self.GRO_TOA_CK.setGeometry(QtCore.QRect(380, 610, 42, 22))
        self.GRO_TOA_CK.setMaximum(1)
        self.GRO_TOA_CK.setProperty("value", 1)
        self.GRO_TOA_CK.setObjectName("GRO_TOA_CK")
        self.GRO_TOA_CK_Labe = QtWidgets.QLabel(self.centralwidget)
        self.GRO_TOA_CK_Labe.setGeometry(QtCore.QRect(291, 610, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.GRO_TOA_CK_Labe.setFont(font)
        self.GRO_TOA_CK_Labe.setObjectName("GRO_TOA_CK_Labe")
        self.GRO_TOARST_N = QtWidgets.QSpinBox(self.centralwidget)
        self.GRO_TOARST_N.setGeometry(QtCore.QRect(610, 610, 42, 22))
        self.GRO_TOARST_N.setMaximum(1)
        self.GRO_TOARST_N.setProperty("value", 1)
        self.GRO_TOARST_N.setObjectName("GRO_TOARST_N")
        self.GRO_TOA_Latch = QtWidgets.QSpinBox(self.centralwidget)
        self.GRO_TOA_Latch.setGeometry(QtCore.QRect(840, 610, 42, 22))
        self.GRO_TOA_Latch.setMaximum(1)
        self.GRO_TOA_Latch.setProperty("value", 1)
        self.GRO_TOA_Latch.setObjectName("GRO_TOA_Latch")
        self.GRO_Start_Label = QtWidgets.QLabel(self.centralwidget)
        self.GRO_Start_Label.setGeometry(QtCore.QRect(91, 610, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.GRO_Start_Label.setFont(font)
        self.GRO_Start_Label.setObjectName("GRO_Start_Label")
        self.GRO_Configuration_Label = QtWidgets.QLabel(self.centralwidget)
        self.GRO_Configuration_Label.setGeometry(QtCore.QRect(10, 580, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.GRO_Configuration_Label.setFont(font)
        self.GRO_Configuration_Label.setObjectName("GRO_Configuration_Label")
        self.GRO_Start = QtWidgets.QSpinBox(self.centralwidget)
        self.GRO_Start.setGeometry(QtCore.QRect(160, 610, 42, 22))
        self.GRO_Start.setMaximum(1)
        self.GRO_Start.setObjectName("GRO_Start")
        self.GRO_TOA_Latch_Label = QtWidgets.QLabel(self.centralwidget)
        self.GRO_TOA_Latch_Label.setGeometry(QtCore.QRect(737, 610, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.GRO_TOA_Latch_Label.setFont(font)
        self.GRO_TOA_Latch_Label.setObjectName("GRO_TOA_Latch_Label")
        self.GRO_TOARST_N_Label = QtWidgets.QLabel(self.centralwidget)
        self.GRO_TOARST_N_Label.setGeometry(QtCore.QRect(505, 610, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.GRO_TOARST_N_Label.setFont(font)
        self.GRO_TOARST_N_Label.setObjectName("GRO_TOARST_N_Label")
        self.GRO_TOTRST_N = QtWidgets.QSpinBox(self.centralwidget)
        self.GRO_TOTRST_N.setGeometry(QtCore.QRect(380, 640, 42, 22))
        self.GRO_TOTRST_N.setMaximum(1)
        self.GRO_TOTRST_N.setProperty("value", 1)
        self.GRO_TOTRST_N.setObjectName("GRO_TOTRST_N")
        self.GRO_TOTRST_N_Label = QtWidgets.QLabel(self.centralwidget)
        self.GRO_TOTRST_N_Label.setGeometry(QtCore.QRect(273, 640, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.GRO_TOTRST_N_Label.setFont(font)
        self.GRO_TOTRST_N_Label.setObjectName("GRO_TOTRST_N_Label")
        self.GRO_TOT_CK_Label = QtWidgets.QLabel(self.centralwidget)
        self.GRO_TOT_CK_Label.setGeometry(QtCore.QRect(70, 640, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.GRO_TOT_CK_Label.setFont(font)
        self.GRO_TOT_CK_Label.setObjectName("GRO_TOT_CK_Label")
        self.GRO_TOT_CK = QtWidgets.QSpinBox(self.centralwidget)
        self.GRO_TOT_CK.setGeometry(QtCore.QRect(160, 640, 42, 22))
        self.GRO_TOT_CK.setMaximum(1)
        self.GRO_TOT_CK.setProperty("value", 1)
        self.GRO_TOT_CK.setObjectName("GRO_TOT_CK")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(321, 700, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.Pulse_Sel_Label = QtWidgets.QLabel(self.centralwidget)
        self.Pulse_Sel_Label.setGeometry(QtCore.QRect(68, 540, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Pulse_Sel_Label.setFont(font)
        self.Pulse_Sel_Label.setObjectName("Pulse_Sel_Label")
        self.Pulse_Sel = QtWidgets.QSpinBox(self.centralwidget)
        self.Pulse_Sel.setGeometry(QtCore.QRect(160, 540, 42, 22))
        self.Pulse_Sel.setMaximum(255)
        self.Pulse_Sel.setProperty("value", 3)
        self.Pulse_Sel.setObjectName("Pulse_Sel")
        self.TDCRawData_Sel = QtWidgets.QSpinBox(self.centralwidget)
        self.TDCRawData_Sel.setGeometry(QtCore.QRect(610, 640, 42, 22))
        self.TDCRawData_Sel.setMaximum(1)
        self.TDCRawData_Sel.setObjectName("TDCRawData_Sel")
        self.TDCRawData_Sel_Label = QtWidgets.QLabel(self.centralwidget)
        self.TDCRawData_Sel_Label.setGeometry(QtCore.QRect(502, 640, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TDCRawData_Sel_Label.setFont(font)
        self.TDCRawData_Sel_Label.setObjectName("TDCRawData_Sel_Label")
        self.I2C_Configuration_Label = QtWidgets.QLabel(self.centralwidget)
        self.I2C_Configuration_Label.setGeometry(QtCore.QRect(10, 670, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.I2C_Configuration_Label.setFont(font)
        self.I2C_Configuration_Label.setObjectName("I2C_Configuration_Label")
        self.Subordinate_Addr_Label = QtWidgets.QLabel(self.centralwidget)
        self.Subordinate_Addr_Label.setGeometry(QtCore.QRect(85, 710, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Subordinate_Addr_Label.setFont(font)
        self.Subordinate_Addr_Label.setObjectName("Subordinate_Addr_Label")
        self.Salve_Addr = QtWidgets.QComboBox(self.centralwidget)
        self.Salve_Addr.setGeometry(QtCore.QRect(158, 710, 51, 22))
        self.Salve_Addr.setObjectName("Salve_Addr")
        self.Salve_Addr.addItem("")
        self.Salve_Addr.addItem("")
        ETROC1_TDC_TEST_GUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ETROC1_TDC_TEST_GUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 899, 21))
        self.menubar.setObjectName("menubar")
        ETROC1_TDC_TEST_GUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ETROC1_TDC_TEST_GUI)
        self.statusbar.setObjectName("statusbar")
        ETROC1_TDC_TEST_GUI.setStatusBar(self.statusbar)

        self.retranslateUi(ETROC1_TDC_TEST_GUI)
        self.pushButton.clicked['bool'].connect(self.pushButton_clicked)
        self.Pulse_enableRx.valueChanged['int'].connect(self.Pulse_enableRx_valueChanged)
        self.Clk40M_enableRx.valueChanged['int'].connect(self.Clk40M_enableRx_valueChanged)
        self.Clk320M_enableRx.valueChanged['int'].connect(self.Clk320M_enableRx_valueChanged)
        self.Clk1G28_enableRx.valueChanged['int'].connect(self.Clk1G28_enableRx_valueChanged)
        self.Pulse_invertData.valueChanged['int'].connect(self.Pulse_invertData_valueChanged)
        self.Clk40M_invertData.valueChanged['int'].connect(self.Clk40M_invertData_valueChanged)
        self.Clk320M_invertData.valueChanged['int'].connect(self.Clk320M_invertData_valueChanged)
        self.Clk1G28_invertData.valueChanged['int'].connect(self.Clk1G28_invertData_valueChanged)
        self.Pulse_enableTermination.valueChanged['int'].connect(self.Pulse_enableTermination_valueChanged)
        self.Clk40M_enableTermination.valueChanged['int'].connect(self.Clk40M_enableTermination_valueChanged)
        self.Clk320M_enableTermination.valueChanged['int'].connect(self.Clk320M_enableTermination_valueChanged)
        self.Clk1G28_enableTermination.valueChanged['int'].connect(self.Clk1G28_enableTermination_valueChanged)
        self.Pulse_setCommonMode.valueChanged['int'].connect(self.Pulse_setCommonMode_valueChanged)
        self.Clk40M_setCommonMode.valueChanged['int'].connect(self.Clk40M_setCommonMode_valueChanged)
        self.Clk320M_setCommonMode.valueChanged['int'].connect(self.Clk320M_setCommonMode_valueChanged)
        self.Clk1G28_setCommonMode.valueChanged['int'].connect(self.Clk1G28_setCommonMode_valueChanged)
        self.Pulse_equalizer.valueChanged['int'].connect(self.Pulse_equalizer_valueChanged)
        self.Clk40M_equalizer.valueChanged['int'].connect(self.Clk40M_equalizer_valueChanged)
        self.Clk320M_equalizer.valueChanged['int'].connect(self.Clk320M_equalizer_valueChanged)
        self.Clk1G28_equalizer.valueChanged['int'].connect(self.Clk1G28_equalizer_valueChanged)
        self.TDC_enable.valueChanged['int'].connect(self.TDC_enable_valueChanged)
        self.TDC_testMode.valueChanged['int'].connect(self.TDC_testMode_valueChanged)
        self.TDC_selRawCode.valueChanged['int'].connect(self.TDC_selRawCode_valueChanged)
        self.TDC_resetn.valueChanged['int'].connect(self.TDC_resetn_valueChanged)
        self.TDC_polaritySel.valueChanged['int'].connect(self.TDC_polaritySel_valueChanged)
        self.TDC_autoReset.valueChanged['int'].connect(self.TDC_autoReset_valueChanged)
        self.TDC_enableMon.valueChanged['int'].connect(self.TDC_enableMon_valueChanged)
        self.TDC_timeStampMode.valueChanged['int'].connect(self.TDC_timeStampMode_valueChanged)
        self.TDC_leve.valueChanged['int'].connect(self.TDC_level_valueChanged)
        self.TDC_offset.valueChanged['int'].connect(self.TDC_offset_valueChanged)
        self.DMRO_enable.valueChanged['int'].connect(self.DMRO_enable_valueChanged)
        self.DMRO_testMode.valueChanged['int'].connect(self.DMRO_testMode_valueChanged)
        self.DMRO_reverse.valueChanged['int'].connect(self.DMRO_reverse_valueChanged)
        self.DMRO_resetn.valueChanged['int'].connect(self.DMRO_resetn_valueChanged)
        self.DMRO_revclk.valueChanged['int'].connect(self.DMRO_revclk_valueChanged)
        self.Dataout_AmplSel.valueChanged['int'].connect(self.Dataout_AmplSel_valueChanged)
        self.Dataout_disCMLDriver_BIAS.valueChanged['int'].connect(self.Dataout_disCMLDriver_BIAS_valueChanged)
        self.Clk40Mout_AmplSel.valueChanged['int'].connect(self.Clk40Mout_AmplSel_valueChanged)
        self.Clk40Mout_disCMLDriver_BIAS.valueChanged['int'].connect(self.Clk40Mout_disCMLDriver_BIAS_valueChanged)
        self.GROout_AmplSel.valueChanged['int'].connect(self.GROout_AmplSel_valueChanged)
        self.GROout_disCMLDriver_BIAS.valueChanged['int'].connect(self.GROout_disCMLDriver_BIAS_valueChanged)
        self.Dataout_Sel.valueChanged['int'].connect(self.Dataout_Sel_valueChanged)
        self.Clk40M_Sel.valueChanged['int'].connect(self.Clk40M_Sel_valueChanged)
        self.Clk40M_Psel.valueChanged['int'].connect(self.Clk40M_Psel_valueChanged)
        self.Clk320M_Sel.valueChanged['int'].connect(self.Clk320M_Sel_valueChanged)
        self.Clk320M_Psel.valueChanged['int'].connect(self.Clk320M_Psel_valueChanged)
        self.Pulse_Sel.valueChanged['int'].connect(self.Pulse_Sel_valueChanged)
        self.GRO_Start.valueChanged['int'].connect(self.GRO_Start_valueChanged)
        self.GRO_TOA_CK.valueChanged['int'].connect(self.GRO_TOA_CK_valueChanged)
        self.GRO_TOARST_N.valueChanged['int'].connect(self.GRO_TOARST_N_valueChanged)
        self.GRO_TOA_Latch.valueChanged['int'].connect(self.GRO_TOA_Latch_valueChanged)
        self.GRO_TOT_CK.valueChanged['int'].connect(self.GRO_TOT_CK_valueChanged)
        self.GRO_TOTRST_N.valueChanged['int'].connect(self.GRO_TOTRST_N_valueChanged)
        self.TDCRawData_Sel.valueChanged['int'].connect(self.TDCRawData_Sel_valueChanged)
        self.Salve_Addr.currentIndexChanged['int'].connect(self.Salve_Addr_currentIndexChanged)
        QtCore.QMetaObject.connectSlotsByName(ETROC1_TDC_TEST_GUI)

    def retranslateUi(self, ETROC1_TDC_TEST_GUI):
        _translate = QtCore.QCoreApplication.translate
        ETROC1_TDC_TEST_GUI.setWindowTitle(_translate("ETROC1_TDC_TEST_GUI", "MainWindow"))
        self.Dataout_AmplSel_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Dataout_AmplSel[2:0]"))
        self.Clk40Mout_disCMLDriver_BIAS_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Clk40Mout_disCMLDriver_BIAS"))
        self.Input_eRx_Configuration_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Input eRx Configuration"))
        self.Pulse_enableRx_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Pulse_enableRx"))
        self.Pulse_invertData_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Pulse_invertData"))
        self.Pulse_enableTermination_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Pulse_enableTermination"))
        self.Pulse_setCommonMode_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Pulse_setCommonMode"))
        self.Pulse_equalizer_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Pulse_equalizer[1:0]"))
        self.Clk40M_equalizer_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Clk40M_equalizer[1:0]"))
        self.Clk40M_setCommonMode_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Clk40M_setCommonMode"))
        self.Clk40M_enableTermination_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Clk40M_enableTermination"))
        self.Clk40M_invertData_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Clk40M_invertData"))
        self.Clk40M_enableRx_Labe.setText(_translate("ETROC1_TDC_TEST_GUI", "Clk40M_enableRx"))
        self.Clk320M_setCommonMode_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Clk320M_setCommonMode"))
        self.Clk320M_equalizer_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Clk320M_equalizer[1:0]"))
        self.Clk320M_enableTermination_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Clk320M_enableTermination"))
        self.Clk320M_invertData_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Clk320M_invertData"))
        self.Clk320M_enableRx_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Clk320M_enableRx"))
        self.Clk1G28_setCommonMode_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Clk1G28_setCommonMode"))
        self.Clk1G28_equalizer_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Clk1G28_equalizer[1:0]"))
        self.Clk1G28_enableTermination_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Clk1G28_enableTermination"))
        self.Clk1G28_invertData_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Clk1G28_invertData"))
        self.Clk1G28_enableRx_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Clk1G28_enableRx"))
        self.TDC_Configuration_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "TDC Configuration"))
        self.TDC_enable_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "TDC_enable"))
        self.TDC_testMode_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "TDC_testMode"))
        self.TDC_selRawCode_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "TDC_selRawCode"))
        self.TDC_resetn_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "TDC_resetn"))
        self.TDC_enableMon_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "TDC_enableMon"))
        self.TDC_polaritySel_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "TDC_polaritySel"))
        self.TDC_autoReset_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "TDC_autoReset"))
        self.TDC_level_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "TDC_level[2:0]"))
        self.TDC_timeStampMode_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "TDC_timeStampMode"))
        self.TDC_offset_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "TDC_offset[6:0]"))
        self.DMRO_Configuration_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "DMRO Configuration"))
        self.DMRO_resetn_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "DMRO_resetn"))
        self.DMRO_enable_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "DMRO_enable"))
        self.DMRO_testMode_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "DMRO_testMode"))
        self.DMRO_reverse_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "DMRO_reverse"))
        self.DMRO_revclk_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "DMRO_revclk"))
        self.Output_TX_Configuration_Labe.setText(_translate("ETROC1_TDC_TEST_GUI", "Output TX Configuration"))
        self.Dataout_disCMLDriver_BIAS_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Dataout_disCMLDriver_BIAS"))
        self.Clk40Mout_AmplSel_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Clk40Mout_AmplSel[2:0]"))
        self.Clock_Configuration_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Clock Configuration"))
        self.Clk40M_Psel_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Clk40M_Psel"))
        self.Clk40M_Sel_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Clk40M_Sel"))
        self.Clk320M_Sel_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Clk320M_Sel"))
        self.Clk320M_Psel_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Clk320M_Psel"))
        self.GROout_disCMLDriver_BIAS_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "GROout_disCMLDriver_BIAS"))
        self.GROout_AmplSel_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "GROout_AmplSel[2:0]"))
        self.Dataout_Sel_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Dataout_Sel"))
        self.GRO_TOA_CK_Labe.setText(_translate("ETROC1_TDC_TEST_GUI", "GRO_TOA_CK"))
        self.GRO_Start_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "GRO_Start"))
        self.GRO_Configuration_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "GRO Configuration"))
        self.GRO_TOA_Latch_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "GRO_TOA_Latch"))
        self.GRO_TOARST_N_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "GRO_TOARST_N"))
        self.GRO_TOTRST_N_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "GRO_TOTRST_N"))
        self.GRO_TOT_CK_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "GRO_TOT_CK"))
        self.pushButton.setText(_translate("ETROC1_TDC_TEST_GUI", "Write_I2C"))
        self.Pulse_Sel_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Pulse_Sel[7:0]"))
        self.TDCRawData_Sel_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "TDCRawData_Sel"))
        self.I2C_Configuration_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "I2C Configuration"))
        self.Subordinate_Addr_Label.setText(_translate("ETROC1_TDC_TEST_GUI", "Subordinate_Addr"))
        self.Salve_Addr.setItemText(0, _translate("ETROC1_TDC_TEST_GUI", "0x22"))
        self.Salve_Addr.setItemText(1, _translate("ETROC1_TDC_TEST_GUI", "0x23"))

    def Salve_Addr_currentIndexChanged(self):
        winsound.Beep(1000, 100)
        if self.Salve_Addr.currentText() == "0x22":
            I2C_Subordinate_Addr = 0x22
            print("I2C Subordinate address: 0x22")
        else:
            I2C_Subordinate_Addr = 0x22
            print("I2C Subordinate address: 0x23")

    def Pulse_enableRx_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Pulse_enableRx(self.Pulse_enableRx.value())

    def Clk40M_enableRx_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Clk40M_enableRx(self.Clk40M_enableRx.value())

    def Clk320M_enableRx_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Clk320M_enableRx(self.Clk320M_enableRx.value())

    def Clk1G28_enableRx_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Clk1G28_enableRx(self.Clk1G28_enableRx.value())

    def Pulse_invertData_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Pulse_invertData(self.Pulse_invertData.value())

    def Clk40M_invertData_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Clk40M_invertData(self.Clk40M_invertData.value())

    def Clk320M_invertData_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Clk320M_invertData(self.Clk320M_invertData.value())

    def Clk1G28_invertData_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Clk1G28_invertData(self.Clk1G28_invertData.value())

    def Pulse_enableTermination_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Pulse_enableTermination(self.Pulse_enableTermination.value())

    def Clk40M_enableTermination_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Clk40M_enableTermination(self.Clk40M_enableTermination.value())

    def Clk320M_enableTermination_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Clk320M_enableTermination(self.Clk320M_enableTermination.value())

    def Clk1G28_enableTermination_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Clk1G28_enableTermination(self.Clk1G28_enableTermination.value())

    def Pulse_setCommonMode_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Pulse_setCommonMode(self.Pulse_setCommonMode.value())

    def Clk40M_setCommonMode_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Clk40M_setCommonMode(self.Clk40M_setCommonMode.value())

    def Clk320M_setCommonMode_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Clk320M_setCommonMode(self.Clk320M_setCommonMode.value())

    def Clk1G28_setCommonMode_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Clk1G28_setCommonMode(self.Clk1G28_setCommonMode.value())

    def Pulse_equalizer_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Pulse_equalizer(self.Pulse_equalizer.value())

    def Clk40M_equalizer_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Clk40M_equalizer(self.Clk40M_equalizer.value())

    def Clk320M_equalizer_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Clk320M_equalizer(self.Clk320M_equalizer.value())

    def Clk1G28_equalizer_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Clk1G28_equalizer(self.Clk1G28_equalizer.value())

    def TDC_enable_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_TDC_enable(self.TDC_enable.value())

    def TDC_testMode_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_TDC_testMode(self.TDC_testMode.value())

    def TDC_selRawCode_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_TDC_selRawCode(self.TDC_selRawCode.value())

    def TDC_resetn_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_TDC_resetn(self.TDC_resetn.value())

    def TDC_polaritySel_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_TDC_polaritySel(self.TDC_polaritySel.value())

    def TDC_autoReset_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_TDC_autoReset(self.TDC_autoReset.value())

    def TDC_enableMon_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_TDC_enableMon(self.TDC_enableMon.value())

    def TDC_timeStampMode_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_TDC_timeStampMode(self.TDC_timeStampMode.value())

    def TDC_level_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_TDC_level(self.TDC_level.value())

    def TDC_offset_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_TDC_offset(self.TDC_offset.value())

    def DMRO_enable_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_DMRO_enable(self.DMRO_enable.value())

    def DMRO_testMode_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_DMRO_testMode(self.DMRO_testMode.value())

    def DMRO_reverse_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_DMRO_reverse(self.DMRO_reverse.value())

    def DMRO_resetn_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_DMRO_resetn(self.DMRO_resetn.value())

    def DMRO_revclk_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_DMRO_revclk(self.DMRO_revclk.value())

    def Dataout_AmplSel_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Dataout_AmplSel(self.Dataout_AmplSel.value())

    def Dataout_disCMLDriver_BIAS_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Dataout_disCMLDriver_BIAS(self.Dataout_disCMLDriver_BIAS.value())

    def Clk40Mout_AmplSel_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Clk40Mout_AmplSel(self.Clk40Mout_AmplSel.value())

    def Clk40Mout_disCMLDriver_BIAS_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Clk40Mout_disCMLDriver_BIAS(self.Clk40Mout_disCMLDriver_BIAS.value())

    def GROout_AmplSel_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_GROout_AmplSel(self.GROout_AmplSel.value())

    def GROout_disCMLDriver_BIAS_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_GROout_disCMLDriver_BIAS(self.GROout_disCMLDriver_BIAS.value())

    def Dataout_Sel_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Dataout_Sel(self.Dataout_Sel.value())

    def Clk40M_Sel_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Clk40M_Sel(self.Clk40M_Sel.value())

    def Clk40M_Psel_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Clk40M_Psel(self.Clk40M_Psel.value())

    def Clk320M_Sel_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Clk320M_Sel(self.Clk320M_Sel.value())

    def Clk320M_Psel_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Clk320M_Psel(self.Clk320M_Psel.value())

    def Pulse_Sel_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_Pulse_Sel(self.Pulse_Sel.value())

    def GRO_Start_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_GRO_Start(self.GRO_Start.value())

    def GRO_TOA_CK_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_GRO_TOA_CK(self.GRO_TOA_CK.value())

    def GRO_TOARST_N_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_GRO_TOARST_N(self.GRO_TOARST_N.value())

    def GRO_TOA_Latch_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_GRO_TOA_Latch(self.GRO_TOA_Latch.value())

    def GRO_TOT_CK_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_GRO_TOT_CK(self.GRO_TOT_CK.value())

    def GRO_TOTRST_N_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_GRO_TOTRST_N(self.GRO_TOTRST_N.value())

    def TDCRawData_Sel_valueChanged(self):
        winsound.Beep(1000, 100)
        ETROC_TDCReg.set_TDCRawData_Sel(self.TDCRawData_Sel.value())

    def pushButton_clicked(self):
        winsound.Beep(2000, 500)
        TDC_I2C_Reg = ETROC_TDCReg.get_config_vector()
        print("TDC I2C Write in data:")
        print(TDC_I2C_Reg)
        for i in range(len(TDC_I2C_Reg)):
            iic_write(1, I2C_Subordinate_Addr, 0, i, TDC_I2C_Reg[i])
        print("TDC I2C Read back data:")
        iic_read_val = []
        for j in range(len(TDC_I2C_Reg)):
            iic_read_val += [iic_read(0, I2C_Subordinate_Addr, 1, j)]
        print(iic_read_val)

if __name__ == "__main__":
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)	#initial socket
    s.connect((hostname, port))								#connect socket
    cmd_interpret = command_interpret(s)					#Class instance
    app = QtWidgets.QApplication(sys.argv)
    ETROC1_TDC_TEST_GUI = QtWidgets.QMainWindow()
    ui = Ui_ETROC1_TDC_TEST_GUI()
    ui.setupUi(ETROC1_TDC_TEST_GUI)
    ETROC_TDCReg = ETROC1_TDCReg()
    ETROC1_TDC_TEST_GUI.show()
    sys.exit(app.exec_())
    s.close()								#close socket
